[tool.poetry]
name = "linkml-transformer"
version = "0.1.0"
description = ""
authors = ["cmungall <cjm@berkeleybop.org>"]

[tool.poetry.dependencies]
python = "^3.9"
linkml-runtime = "^1.2.16"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
linkml = "^1.2.15"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
